before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: gBi1EzLA1KgSYa/mRMSoIJW+it0nw2EvXLAMI12NVT4uIdeJ9STONE/CCLxkRIYm0CY4cvzW28MyQB7Vm77ELtplX5trFCWd3zfeOVzZzToXWq4VM1VDlJylVLRQk/l0A0i6EzF0fQ9jyGWrxE0A8c1+NJvu+Tr6Owc7MBk88xGDKIlqwZxpZKogyAITBR8M+ovtICzpUYjdaN52PJaBCwp1UfIDRBNABwr8d11WSQehyzaX8SOjTrHVD5LB0NcKdkgGmMzIRC75c8W/LKNVDX12dSKvX7Yy23W98rNwhx1QaJxhhYql0WCjbJMfYgX4tVuXzQxoLWq+r+reyE2DigLCmYruOib+oGzV4kIRK1QOsZqYc557oaTl0i3gcmMmSlwgdqOsK5nkFEbrd3zAVwbJhnotMfYrehI8tY3IxcjMgdsEgEfitfT/r3clx4lR0GUkP80XebWrTUmR1UqHkeyjcCTlYX8gAaDc2XybYTzb29J7xg7IPfd6Q+QZseTH5QYpX1LCx4kAT9vPCVXtFc6cnwrhUrCeJI17jjW0Pm4sNzari6y+8+4WCcdjummOx5R7mv7wRvzeT3ALj2aIfrXcOjk1sxCJ2sGAEbr4KS45DdkLiiOtB6QRE0fPZ1FI65iGdu29sKmfuTSTzTfDYoW657qBndrJAoQaHdmBar4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
